### ISSUE TITLE
BITE Tokenization and BERT fine-tuning Query

### ISSUE THREAD

**Issue by ashispapu** [salesforce/bite#1]
Thank you for sharing your insightful research work and implementation. While trying to understand the implementation, got stuck in one fundamental step. Let me explain it .

Below is the step BITE follows with Wordpiece tokenizer for the tokenization.
`Input text --> Whitespace/punctuation based tokenizer --> Base Inflection Encoding --> Wordpiece Sub Tokenizer --> Integer IDs for tokens --> Model Training/Finetuning`

In this process, we update the tokenizer vocab list with the new tokens based on the Inflection symbols(POS tags). Since these are completely new tokens for the tokenizer, the base model needs to learn all those syntax and semantics during the pre-training. And the first layer of the model(here, BERT base) is embedding layer, which has already a fixed dimension ( ~30K, 768) based on the initial pre-training. How does the BITE manage to incorporate new tokens while fine tuning tasks like SQuAD and MNLI .

According to me, we need to pre-train the model (here, BERT base) on the updated vocabs(which includes the Inflection symbols + Original BERT base Wordpiece vocabs) and then fine tune it on the specific tasks like SQuAD and MNLI. Please help me to clarify this confusion.

The Next one is below.
For example, the word  `took` would be tokenized as below.
` took ---> BITE---> take + [VBD] ------> Wordpiece ---> [token ids] `

In the above case, if the word `take` is again tokenized to different sub-tokens(for example,` tak, ##e`) by wordpiece(if the exact token is not available in wordpiece vocab list), How is it going to preserve the root(lemma) intact during the training.

Would appreciate  your comments.

**Comment by samsontmr** [comment]
> According to me, we need to pre-train the model (here, BERT base) on the updated vocabs(which includes the Inflection symbols + Original BERT base Wordpiece vocabs) and then fine tune it on the specific tasks like SQuAD and MNLI. Please help me to clarify this confusion.

Since all parameters are updated during fine-tuning, we found fine-tuning to be enough for the model to adapt to the new tokens. It is possible that doing more pretraining with the new tokens would improve downstream performance further but it's not necessary to achieve a similar level of performance as the control.

> In the above case, if the word take is again tokenized to different sub-tokens(for example, tak, ##e) by wordpiece(if the exact token is not available in wordpiece vocab list), How is it going to preserve the root(lemma) intact during the training

We do not need to ensure the lemma is a single token for improved robustness; we only need the lemmas of different inflected forms belonging to the same lexeme to be represented similarly. For example, using a hypothetical tokenization,
`took -> take [VBD] -> [ta, ##ke, VBD]`
`taking -> take [VBG] -> [ta, ##ke, VBG]`
`take -> take -> [ta, ##ke]`

 as opposed to
`took -> [too, ##k]`
`taking -> [ta, ##king]`
`take -> take -> [ta, ##ke]`

You can easily see that the final wordpiece representations in the latter tokenization are all very different from each other, compared to the former (BITE).

**Comment by ashispapu** [comment]
Thank you for the response.
`Since all parameters are updated during fine-tuning, we found fine-tuning to be enough for the model to adapt to the new tokens. It is possible that doing more pretraining with the new tokens would improve downstream performance further but it's not necessary to achieve a similar level of performance as the control.`

So, with `BITE + wordpiece`, fine-tuning is done on specific tasks for all the parameters. After adding new tokens(POS tags) to wordpiece vocab list, the initial embedding layer must be changed to new count of tokens`(~30k + POS tokens, 768)` for fine-tuned BERT base model.This changes would be reflected in the `config.json` of the updated model. Is that correct understanding ?
Are these models available publicly for reference.

**Comment by samsontmr** [comment]
We did not add new tokens to the vocab but used some of the existing unused ones. The modified vocab for BERT-base can be found here: https://github.com/salesforce/bite/blob/master/src/bite/bert_base_wordpiece_vocab.txt

**Comment by ashispapu** [comment]
Thanks for the clarification.
